//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IInvoiceLHDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/10/20 14:13:56
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IInvoiceLHDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.InvoiceLHDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.InvoiceLHDetail e);
		
		void Update(Model.InvoiceLHDetail e);
		
		IList<Model.InvoiceLHDetail> Select();
		
		IList<Model.InvoiceLHDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
