//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPackingInvoiceDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/12/2 16:05:25
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPackingInvoiceDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PackingInvoiceDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PackingInvoiceDetail e);
		
		void Update(Model.PackingInvoiceDetail e);
		
		IList<Model.PackingInvoiceDetail> Select();
		
		IList<Model.PackingInvoiceDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
