//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPackingListDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/11/11 17:33:41
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPackingListDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PackingListDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PackingListDetail e);
		
		void Update(Model.PackingListDetail e);
		
		IList<Model.PackingListDetail> Select();
		
		IList<Model.PackingListDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
