//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPackingInvoiceHeaderAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/12/2 16:05:25
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPackingInvoiceHeaderAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PackingInvoiceHeader Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PackingInvoiceHeader e);
		
		void Update(Model.PackingInvoiceHeader e);
		
		IList<Model.PackingInvoiceHeader> Select();
		
		IList<Model.PackingInvoiceHeader> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PackingInvoiceHeader e);
		
		bool HasRowsAfter(Model.PackingInvoiceHeader e);
		
		Model.PackingInvoiceHeader GetFirst();
		
		Model.PackingInvoiceHeader GetLast();
		
		Model.PackingInvoiceHeader GetPrev(Model.PackingInvoiceHeader e);
		
		Model.PackingInvoiceHeader GetNext(Model.PackingInvoiceHeader e);

	}
}
