//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPackingListHeaderAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/11/11 17:33:41
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPackingListHeaderAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PackingListHeader Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PackingListHeader e);
		
		void Update(Model.PackingListHeader e);
		
		IList<Model.PackingListHeader> Select();
		
		IList<Model.PackingListHeader> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PackingListHeader e);
		
		bool HasRowsAfter(Model.PackingListHeader e);
		
		Model.PackingListHeader GetFirst();
		
		Model.PackingListHeader GetLast();
		
		Model.PackingListHeader GetPrev(Model.PackingListHeader e);
		
		Model.PackingListHeader GetNext(Model.PackingListHeader e);

	}
}
