//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPortAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/11/11 17:33:41
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPortAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.Port Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.Port e);
		
		void Update(Model.Port e);
		
		IList<Model.Port> Select();
		
		IList<Model.Port> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

		bool Exists(string id);
		
		Model.Port GetById(string id);
		
		bool ExistsExcept(Model.Port e);
		
	}
}
