//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IProformaInvoiceDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/3/13 20:30:28
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IProformaInvoiceDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ProformaInvoiceDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ProformaInvoiceDetail e);
		
		void Update(Model.ProformaInvoiceDetail e);
		
		IList<Model.ProformaInvoiceDetail> Select();
		
		IList<Model.ProformaInvoiceDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
