//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IProductItemNoAccessor.autogenerated.cs
// author: mayanjun
// create date：2020/11/29 12:58:22
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IProductItemNoAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ProductItemNo Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ProductItemNo e);
		
		void Update(Model.ProductItemNo e);
		
		IList<Model.ProductItemNo> Select();
		
		IList<Model.ProductItemNo> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.ProductItemNo e);
		
		bool HasRowsAfter(Model.ProductItemNo e);
		
		Model.ProductItemNo GetFirst();
		
		Model.ProductItemNo GetLast();
		
		Model.ProductItemNo GetPrev(Model.ProductItemNo e);
		
		Model.ProductItemNo GetNext(Model.ProductItemNo e);

	}
}
