//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IProformaInvoiceAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/3/13 18:44:59
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IProformaInvoiceAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ProformaInvoice Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ProformaInvoice e);
		
		void Update(Model.ProformaInvoice e);
		
		IList<Model.ProformaInvoice> Select();
		
		IList<Model.ProformaInvoice> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.ProformaInvoice e);
		
		bool HasRowsAfter(Model.ProformaInvoice e);
		
		Model.ProformaInvoice GetFirst();
		
		Model.ProformaInvoice GetLast();
		
		Model.ProformaInvoice GetPrev(Model.ProformaInvoice e);
		
		Model.ProformaInvoice GetNext(Model.ProformaInvoice e);

	}
}
