//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ExchangeRateAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/11/15 23:30:49
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class ExchangeRateAccessor
    {
		public Model.ExchangeRate Get(string id)
		{
			return this.Get<Model.ExchangeRate>(id);
		}
		
		public void Insert(Model.ExchangeRate e)
		{
			this.Insert<Model.ExchangeRate>(e);
		}
		
		public void Update(Model.ExchangeRate e)
		{
			this.Update<Model.ExchangeRate>(e);
		}
		
		public IList<Model.ExchangeRate> Select()
		{
			return this.Select<Model.ExchangeRate>();
		}
		
		public IList<Model.ExchangeRate> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.ExchangeRate>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.ExchangeRate>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.ExchangeRate>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.ExchangeRate>();
		}
		public int Count()
		{
			return this.Count<Model.ExchangeRate>();
		}

		public bool Exists(string id)
		{
			return sqlmapper.QueryForObject<bool>("ExchangeRate.exists", id);
		}
		
		public Model.ExchangeRate GetById(string id)
		{
			return sqlmapper.QueryForObject<Model.ExchangeRate>("ExchangeRate.get_by_id", id);
		}
		
		public bool ExistsExcept(Model.ExchangeRate e)
		{
			Hashtable paras = new Hashtable();
			paras.Add("newId", e.Id);
            paras.Add("oldId", Get(e.Id)==null?null:Get(e.Id).Id);
			return sqlmapper.QueryForObject<bool>("ExchangeRate.existsexcept", paras);
		}
		
		
		
		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("ExchangeRate.existsPrimary", id);
		}
    }
}
