//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InformationStateAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/8/20 16:34:49
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class InformationStateAccessor
    {
		public Model.InformationState Get(string id)
		{
			return this.Get<Model.InformationState>(id);
		}
		
		public void Insert(Model.InformationState e)
		{
			this.Insert<Model.InformationState>(e);
		}
		
		public void Update(Model.InformationState e)
		{
			this.Update<Model.InformationState>(e);
		}
		
		public IList<Model.InformationState> Select()
		{
			return this.Select<Model.InformationState>();
		}
		
		public IList<Model.InformationState> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.InformationState>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.InformationState>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.InformationState>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.InformationState>();
		}
		public int Count()
		{
			return this.Count<Model.InformationState>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("InformationState.existsPrimary", id);
		}
    }
}
