//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InformationAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/8/20 16:34:49
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class InformationAccessor
    {
		public Model.Information Get(string id)
		{
			return this.Get<Model.Information>(id);
		}
		
		public void Insert(Model.Information e)
		{
			this.Insert<Model.Information>(e);
		}
		
		public void Update(Model.Information e)
		{
			this.Update<Model.Information>(e);
		}
		
		public IList<Model.Information> Select()
		{
			return this.Select<Model.Information>();
		}
		
		public IList<Model.Information> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.Information>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.Information>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.Information>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.Information>();
		}
		public int Count()
		{
			return this.Count<Model.Information>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("Information.existsPrimary", id);
		}
    }
}
