//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceLHDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/10/20 14:13:56
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class InvoiceLHDetailAccessor
    {
		public Model.InvoiceLHDetail Get(string id)
		{
			return this.Get<Model.InvoiceLHDetail>(id);
		}
		
		public void Insert(Model.InvoiceLHDetail e)
		{
			this.Insert<Model.InvoiceLHDetail>(e);
		}
		
		public void Update(Model.InvoiceLHDetail e)
		{
			this.Update<Model.InvoiceLHDetail>(e);
		}
		
		public IList<Model.InvoiceLHDetail> Select()
		{
			return this.Select<Model.InvoiceLHDetail>();
		}
		
		public IList<Model.InvoiceLHDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.InvoiceLHDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.InvoiceLHDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.InvoiceLHDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.InvoiceLHDetail>();
		}
		public int Count()
		{
			return this.Count<Model.InvoiceLHDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("InvoiceLHDetail.existsPrimary", id);
		}
    }
}
