//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PackingInvoiceHeaderAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/12/2 16:05:25
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PackingInvoiceHeaderAccessor
    {
		public Model.PackingInvoiceHeader Get(string id)
		{
			return this.Get<Model.PackingInvoiceHeader>(id);
		}
		
		public void Insert(Model.PackingInvoiceHeader e)
		{
			this.Insert<Model.PackingInvoiceHeader>(e);
		}
		
		public void Update(Model.PackingInvoiceHeader e)
		{
			this.Update<Model.PackingInvoiceHeader>(e);
		}
		
		public IList<Model.PackingInvoiceHeader> Select()
		{
			return this.Select<Model.PackingInvoiceHeader>();
		}
		
		public IList<Model.PackingInvoiceHeader> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PackingInvoiceHeader>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PackingInvoiceHeader>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PackingInvoiceHeader>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PackingInvoiceHeader>();
		}
		public int Count()
		{
			return this.Count<Model.PackingInvoiceHeader>();
		}
		public bool HasRowsBefore(Model.PackingInvoiceHeader e)
		{
			return sqlmapper.QueryForObject<bool>("PackingInvoiceHeader.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PackingInvoiceHeader e)
		{
			return sqlmapper.QueryForObject<bool>("PackingInvoiceHeader.has_rows_after", e);
		}
		public Model.PackingInvoiceHeader GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PackingInvoiceHeader>("PackingInvoiceHeader.get_first", null);
		}
		public Model.PackingInvoiceHeader GetLast()
		{
			return sqlmapper.QueryForObject<Model.PackingInvoiceHeader>("PackingInvoiceHeader.get_last", null);
		}
		public Model.PackingInvoiceHeader GetNext(Model.PackingInvoiceHeader e)
		{
			return sqlmapper.QueryForObject<Model.PackingInvoiceHeader>("PackingInvoiceHeader.get_next", e);
		}
		public Model.PackingInvoiceHeader GetPrev(Model.PackingInvoiceHeader e)
		{
			return sqlmapper.QueryForObject<Model.PackingInvoiceHeader>("PackingInvoiceHeader.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PackingInvoiceHeader.existsPrimary", id);
		}
    }
}
