//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PackingInvoiceDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/12/2 16:05:25
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PackingInvoiceDetailAccessor
    {
		public Model.PackingInvoiceDetail Get(string id)
		{
			return this.Get<Model.PackingInvoiceDetail>(id);
		}
		
		public void Insert(Model.PackingInvoiceDetail e)
		{
			this.Insert<Model.PackingInvoiceDetail>(e);
		}
		
		public void Update(Model.PackingInvoiceDetail e)
		{
			this.Update<Model.PackingInvoiceDetail>(e);
		}
		
		public IList<Model.PackingInvoiceDetail> Select()
		{
			return this.Select<Model.PackingInvoiceDetail>();
		}
		
		public IList<Model.PackingInvoiceDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PackingInvoiceDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PackingInvoiceDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PackingInvoiceDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PackingInvoiceDetail>();
		}
		public int Count()
		{
			return this.Count<Model.PackingInvoiceDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PackingInvoiceDetail.existsPrimary", id);
		}
    }
}
