//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PortAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/11/11 17:33:41
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PortAccessor
    {
		public Model.Port Get(string id)
		{
			return this.Get<Model.Port>(id);
		}
		
		public void Insert(Model.Port e)
		{
			this.Insert<Model.Port>(e);
		}
		
		public void Update(Model.Port e)
		{
			this.Update<Model.Port>(e);
		}
		
		public IList<Model.Port> Select()
		{
			return this.Select<Model.Port>();
		}
		
		public IList<Model.Port> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.Port>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.Port>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.Port>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.Port>();
		}
		public int Count()
		{
			return this.Count<Model.Port>();
		}

		public bool Exists(string id)
		{
			return sqlmapper.QueryForObject<bool>("Port.exists", id);
		}
		
		public Model.Port GetById(string id)
		{
			return sqlmapper.QueryForObject<Model.Port>("Port.get_by_id", id);
		}
		
		public bool ExistsExcept(Model.Port e)
		{
			Hashtable paras = new Hashtable();
			paras.Add("newId", e.Id);
            paras.Add("oldId", Get(e.PortId)==null?null:Get(e.PortId).Id);
			return sqlmapper.QueryForObject<bool>("Port.existsexcept", paras);
		}
		
		
		
		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("Port.existsPrimary", id);
		}
    }
}
