//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductBarCodeSetAccessor.autogenerated.cs
// author: mayanjun
// create date：2016/3/31 21:50:14
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class ProductBarCodeSetAccessor
    {
		public Model.ProductBarCodeSet Get(string id)
		{
			return this.Get<Model.ProductBarCodeSet>(id);
		}
		
		public void Insert(Model.ProductBarCodeSet e)
		{
			this.Insert<Model.ProductBarCodeSet>(e);
		}
		
		public void Update(Model.ProductBarCodeSet e)
		{
			this.Update<Model.ProductBarCodeSet>(e);
		}
		
		public IList<Model.ProductBarCodeSet> Select()
		{
			return this.Select<Model.ProductBarCodeSet>();
		}
		
		public IList<Model.ProductBarCodeSet> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.ProductBarCodeSet>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.ProductBarCodeSet>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.ProductBarCodeSet>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.ProductBarCodeSet>();
		}
		public int Count()
		{
			return this.Count<Model.ProductBarCodeSet>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("ProductBarCodeSet.existsPrimary", id);
		}
    }
}
