//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductScrapDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2018-01-14 22:36:50
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class ProductScrapDetailAccessor
    {
		public Model.ProductScrapDetail Get(string id)
		{
			return this.Get<Model.ProductScrapDetail>(id);
		}
		
		public void Insert(Model.ProductScrapDetail e)
		{
			this.Insert<Model.ProductScrapDetail>(e);
		}
		
		public void Update(Model.ProductScrapDetail e)
		{
			this.Update<Model.ProductScrapDetail>(e);
		}
		
		public IList<Model.ProductScrapDetail> Select()
		{
			return this.Select<Model.ProductScrapDetail>();
		}
		
		public IList<Model.ProductScrapDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.ProductScrapDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.ProductScrapDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.ProductScrapDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.ProductScrapDetail>();
		}
		public int Count()
		{
			return this.Count<Model.ProductScrapDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("ProductScrapDetail.existsPrimary", id);
		}
    }
}
