//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductItemNoAccessor.autogenerated.cs
// author: mayanjun
// create date：2020/11/29 12:58:22
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class ProductItemNoAccessor
    {
		public Model.ProductItemNo Get(string id)
		{
			return this.Get<Model.ProductItemNo>(id);
		}
		
		public void Insert(Model.ProductItemNo e)
		{
			this.Insert<Model.ProductItemNo>(e);
		}
		
		public void Update(Model.ProductItemNo e)
		{
			this.Update<Model.ProductItemNo>(e);
		}
		
		public IList<Model.ProductItemNo> Select()
		{
			return this.Select<Model.ProductItemNo>();
		}
		
		public IList<Model.ProductItemNo> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.ProductItemNo>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.ProductItemNo>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.ProductItemNo>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.ProductItemNo>();
		}
		public int Count()
		{
			return this.Count<Model.ProductItemNo>();
		}
		public bool HasRowsBefore(Model.ProductItemNo e)
		{
			return sqlmapper.QueryForObject<bool>("ProductItemNo.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.ProductItemNo e)
		{
			return sqlmapper.QueryForObject<bool>("ProductItemNo.has_rows_after", e);
		}
		public Model.ProductItemNo GetFirst()
		{
			return sqlmapper.QueryForObject<Model.ProductItemNo>("ProductItemNo.get_first", null);
		}
		public Model.ProductItemNo GetLast()
		{
			return sqlmapper.QueryForObject<Model.ProductItemNo>("ProductItemNo.get_last", null);
		}
		public Model.ProductItemNo GetNext(Model.ProductItemNo e)
		{
			return sqlmapper.QueryForObject<Model.ProductItemNo>("ProductItemNo.get_next", e);
		}
		public Model.ProductItemNo GetPrev(Model.ProductItemNo e)
		{
			return sqlmapper.QueryForObject<Model.ProductItemNo>("ProductItemNo.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("ProductItemNo.existsPrimary", id);
		}
    }
}
