//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ExchangeRateManager.autogenerated.cs
// author: mayanjun
// create date：2018/11/15 23:30:48
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ExchangeRateManager
    {
		///<summary>
		/// Data accessor of dbo.ExchangeRate
		///</summary>
		private static readonly DA.IExchangeRateAccessor accessor = (DA.IExchangeRateAccessor)Accessors.Get("ExchangeRateAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ExchangeRate Get(string id)
		{
			return accessor.Get(id);
		}
		
		public bool HasRows(string id)
		{
			return accessor.HasRows(id);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool Exists(string id)
		{
			return accessor.Exists(id);
		}
		
		public Model.ExchangeRate GetById(string id)
		{
			return accessor.GetById(id);
		}		
		public bool ExistsExcept(Model.ExchangeRate e)
		{
			return accessor.ExistsExcept(e);
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ExchangeRate> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ExchangeRate> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
