//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InformationManager.autogenerated.cs
// author: mayanjun
// create date：2015/8/20 16:34:49
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class InformationManager
    {
		///<summary>
		/// Data accessor of dbo.Information
		///</summary>
		private static readonly DA.IInformationAccessor accessor = (DA.IInformationAccessor)Accessors.Get("InformationAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.Information Get(string informationId)
		{
			return accessor.Get(informationId);
		}
		
		public bool HasRows(string informationId)
		{
			return accessor.HasRows(informationId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.Information> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.Information> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
