//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceLHManager.autogenerated.cs
// author: mayanjun
// create date：2018/10/20 15:49:33
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class InvoiceLHManager
    {
		///<summary>
		/// Data accessor of dbo.InvoiceLH
		///</summary>
		private static readonly DA.IInvoiceLHAccessor accessor = (DA.IInvoiceLHAccessor)Accessors.Get("InvoiceLHAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.InvoiceLH Get(string invoiceId)
		{
			return accessor.Get(invoiceId);
		}
		
		public bool HasRows(string invoiceId)
		{
			return accessor.HasRows(invoiceId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.InvoiceLH e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.InvoiceLH e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.InvoiceLH GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.InvoiceLH GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.InvoiceLH GetPrev(Model.InvoiceLH e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.InvoiceLH GetNext(Model.InvoiceLH e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.InvoiceLH> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.InvoiceLH> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
