//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceLHDetailManager.autogenerated.cs
// author: mayanjun
// create date：2018/10/20 14:13:56
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class InvoiceLHDetailManager
    {
		///<summary>
		/// Data accessor of dbo.InvoiceLHDetail
		///</summary>
		private static readonly DA.IInvoiceLHDetailAccessor accessor = (DA.IInvoiceLHDetailAccessor)Accessors.Get("InvoiceLHDetailAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.InvoiceLHDetail Get(string invoiceLHDetailId)
		{
			return accessor.Get(invoiceLHDetailId);
		}
		
		public bool HasRows(string invoiceLHDetailId)
		{
			return accessor.HasRows(invoiceLHDetailId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.InvoiceLHDetail> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.InvoiceLHDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
