//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductBarCodeSetManager.autogenerated.cs
// author: mayanjun
// create date：2016/3/31 21:50:14
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ProductBarCodeSetManager
    {
		///<summary>
		/// Data accessor of dbo.ProductBarCodeSet
		///</summary>
		private static readonly DA.IProductBarCodeSetAccessor accessor = (DA.IProductBarCodeSetAccessor)Accessors.Get("ProductBarCodeSetAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ProductBarCodeSet Get(string productBarCodeSetId)
		{
			return accessor.Get(productBarCodeSetId);
		}
		
		public bool HasRows(string productBarCodeSetId)
		{
			return accessor.HasRows(productBarCodeSetId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ProductBarCodeSet> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ProductBarCodeSet> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
