//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductItemNoManager.autogenerated.cs
// author: mayanjun
// create date：2020/11/29 12:58:22
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ProductItemNoManager
    {
		///<summary>
		/// Data accessor of dbo.ProductItemNo
		///</summary>
		private static readonly DA.IProductItemNoAccessor accessor = (DA.IProductItemNoAccessor)Accessors.Get("ProductItemNoAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ProductItemNo Get(string itemNo)
		{
			return accessor.Get(itemNo);
		}
		
		public bool HasRows(string itemNo)
		{
			return accessor.HasRows(itemNo);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.ProductItemNo e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.ProductItemNo e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.ProductItemNo GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.ProductItemNo GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.ProductItemNo GetPrev(Model.ProductItemNo e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.ProductItemNo GetNext(Model.ProductItemNo e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ProductItemNo> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ProductItemNo> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
