//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProformaInvoiceManager.autogenerated.cs
// author: mayanjun
// create date：2019/3/13 18:44:59
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ProformaInvoiceManager
    {
		///<summary>
		/// Data accessor of dbo.ProformaInvoice
		///</summary>
		private static readonly DA.IProformaInvoiceAccessor accessor = (DA.IProformaInvoiceAccessor)Accessors.Get("ProformaInvoiceAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ProformaInvoice Get(string pO)
		{
			return accessor.Get(pO);
		}
		
		public bool HasRows(string pO)
		{
			return accessor.HasRows(pO);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.ProformaInvoice e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.ProformaInvoice e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.ProformaInvoice GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.ProformaInvoice GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.ProformaInvoice GetPrev(Model.ProformaInvoice e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.ProformaInvoice GetNext(Model.ProformaInvoice e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ProformaInvoice> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ProformaInvoice> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
