//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ExchangeRate.autogenerated.cs
// author: mayanjun
// create date：2018/11/15 23:30:49
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class ExchangeRate
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private string _id;

        private int _yearValue;

        private int _monthValue;

        private string _currency;

        private decimal? _upRate;

        private decimal? _middleRate;

        private decimal? _downRate;

        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }

        public int YearValue
        {
            get { return _yearValue; }
            set { _yearValue = value; }
        }

        public int MonthValue
        {
            get { return _monthValue; }
            set { _monthValue = value; }
        }

        public string Currency
        {
            get { return _currency; }
            set { _currency = value; }
        }

        public decimal? UpRate
        {
            get { return _upRate; }
            set { _upRate = value; }
        }

        public decimal? MiddleRate
        {
            get { return _middleRate; }
            set { _middleRate = value; }
        }

        public decimal? DownRate
        {
            get { return _downRate; }
            set { _downRate = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Id = "Id";

        public readonly static string PRO_YearValue = "YearValue";

        public readonly static string PRO_MonthValue = "MonthValue";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Currency = "Currency";

        public readonly static string PRO_UpRate = "UpRate";

        public readonly static string PRO_MiddleRate = "MiddleRate";

        public readonly static string PRO_DownRate = "DownRate";
        #endregion
    }
}