//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：Information.autogenerated.cs
// author: mayanjun
// create date：2015/8/20 16:34:49
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class Information
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _informationId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _informationDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceType;
		
		/// <summary>
		/// 
		/// </summary>
		private string _messageText;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string InformationId
		{
			get 
			{
				return this._informationId;
			}
			set 
			{
				this._informationId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InformationDate
		{
			get 
			{
				return this._informationDate;
			}
			set 
			{
				this._informationDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceId
		{
			get 
			{
				return this._invoiceId;
			}
			set 
			{
				this._invoiceId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceType
		{
			get 
			{
				return this._invoiceType;
			}
			set 
			{
				this._invoiceType = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string MessageText
		{
			get 
			{
				return this._messageText;
			}
			set 
			{
				this._messageText = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InformationId = "InformationId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InformationDate = "InformationDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceId = "InvoiceId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceType = "InvoiceType";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_MessageText = "MessageText";
		

		#endregion
	}
}