//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceLH.autogenerated.cs
// author: mayanjun
// create date：2018/10/20 15:49:33
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class InvoiceLH
	{
		#region Data
		
		/// <summary>
		/// 
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _conveyanceMethodId;
				
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private string _empCreaterId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _empShengguanId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _empShechuId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _empPinjianId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _empDepotId;
		
		/// <summary>
		/// 货运方式
		/// </summary>
		private ConveyanceMethod _conveyanceMethod;
		/// <summary>
		/// 客户
		/// </summary>
		private Customer _customer;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _empCreater;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _empDepot;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _empPinjian;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _empShechu;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _empShengguan;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ConveyanceMethodId
		{
			get 
			{
				return this._conveyanceMethodId;
			}
			set 
			{
				this._conveyanceMethodId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmpCreaterId
		{
			get 
			{
				return this._empCreaterId;
			}
			set 
			{
				this._empCreaterId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmpShengguanId
		{
			get 
			{
				return this._empShengguanId;
			}
			set 
			{
				this._empShengguanId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmpShechuId
		{
			get 
			{
				return this._empShechuId;
			}
			set 
			{
				this._empShechuId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmpPinjianId
		{
			get 
			{
				return this._empPinjianId;
			}
			set 
			{
				this._empPinjianId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmpDepotId
		{
			get 
			{
				return this._empDepotId;
			}
			set 
			{
				this._empDepotId = value;
			}
		}

		/// <summary>
		/// 货运方式
		/// </summary>
		public virtual ConveyanceMethod ConveyanceMethod
		{
			get
			{
				return this._conveyanceMethod;
			}
			set
			{
				this._conveyanceMethod = value;
			}
			
		}
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee EmpCreater
		{
			get
			{
				return this._empCreater;
			}
			set
			{
				this._empCreater = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee EmpDepot
		{
			get
			{
				return this._empDepot;
			}
			set
			{
				this._empDepot = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee EmpPinjian
		{
			get
			{
				return this._empPinjian;
			}
			set
			{
				this._empPinjian = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee EmpShechu
		{
			get
			{
				return this._empShechu;
			}
			set
			{
				this._empShechu = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee EmpShengguan
		{
			get
			{
				return this._empShengguan;
			}
			set
			{
				this._empShengguan = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceId = "InvoiceId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_CustomerId = "CustomerId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ConveyanceMethodId = "ConveyanceMethodId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceDate = "InvoiceDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmpCreaterId = "EmpCreaterId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmpShengguanId = "EmpShengguanId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmpShechuId = "EmpShechuId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmpPinjianId = "EmpPinjianId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmpDepotId = "EmpDepotId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_AuditState = "AuditState";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_AuditEmpId = "AuditEmpId";
		

		#endregion
	}
}