//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceLHDetail.autogenerated.cs
// author: mayanjun
// create date：2018/10/20 14:13:56
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class InvoiceLHDetail
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _invoiceLHDetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceLHId;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _number;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceXODetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _estimateQty;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productUnit;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _boxCapacityQty;
		
		/// <summary>
		/// 
		/// </summary>
		private string _boxNumber;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _boxQty;
		
		/// <summary>
		/// 
		/// </summary>
		private string _note;
		
		/// <summary>
		/// 
		/// </summary>
		private InvoiceLH _invoiceLH;
		/// <summary>
		/// 销售订单货品
		/// </summary>
		private InvoiceXODetail _invoiceXODetail;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string InvoiceLHDetailId
		{
			get 
			{
				return this._invoiceLHDetailId;
			}
			set 
			{
				this._invoiceLHDetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceLHId
		{
			get 
			{
				return this._invoiceLHId;
			}
			set 
			{
				this._invoiceLHId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? Number
		{
			get 
			{
				return this._number;
			}
			set 
			{
				this._number = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceXODetailId
		{
			get 
			{
				return this._invoiceXODetailId;
			}
			set 
			{
				this._invoiceXODetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? EstimateQty
		{
			get 
			{
				return this._estimateQty;
			}
			set 
			{
				this._estimateQty = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductUnit
		{
			get 
			{
				return this._productUnit;
			}
			set 
			{
				this._productUnit = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? BoxCapacityQty
		{
			get 
			{
				return this._boxCapacityQty;
			}
			set 
			{
				this._boxCapacityQty = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string BoxNumber
		{
			get 
			{
				return this._boxNumber;
			}
			set 
			{
				this._boxNumber = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? BoxQty
		{
			get 
			{
				return this._boxQty;
			}
			set 
			{
				this._boxQty = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Note
		{
			get 
			{
				return this._note;
			}
			set 
			{
				this._note = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public virtual InvoiceLH InvoiceLH
		{
			get
			{
				return this._invoiceLH;
			}
			set
			{
				this._invoiceLH = value;
			}
			
		}
		/// <summary>
		/// 销售订单货品
		/// </summary>
		public virtual InvoiceXODetail InvoiceXODetail
		{
			get
			{
				return this._invoiceXODetail;
			}
			set
			{
				this._invoiceXODetail = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceLHDetailId = "InvoiceLHDetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceLHId = "InvoiceLHId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Number = "Number";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceXODetailId = "InvoiceXODetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EstimateQty = "EstimateQty";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductUnit = "ProductUnit";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BoxCapacityQty = "BoxCapacityQty";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BoxNumber = "BoxNumber";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BoxQty = "BoxQty";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Note = "Note";
		

		#endregion
	}
}