//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PackingListDetail.autogenerated.cs
// author: mayanjun
// create date：2018/11/11 17:33:42
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class PackingListDetail
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private string _packingListDetailId;

        /// <summary>
        /// 
        /// </summary>
        private string _packingListHeaderId;

        /// <summary>
        /// 
        /// </summary>
        private string _pLTNo;

        /// <summary>
        /// 
        /// </summary>
        private string _cartonNo;

        /// <summary>
        /// 
        /// </summary>
        private string _pONo;

        /// <summary>
        /// 
        /// </summary>
        private string _productId;

        /// <summary>
        /// 
        /// </summary>
        private decimal? _boxMaxQuantity;

        /// <summary>
        /// 
        /// </summary>
        private decimal? _boxMaxNetWeight;

        /// <summary>
        /// 
        /// </summary>
        private decimal? _boxMaxGrossWeight;

        /// <summary>
        /// 
        /// </summary>
        private decimal? _quantity;

        /// <summary>
        /// 
        /// </summary>
        private decimal? _netWeight;

        /// <summary>
        /// 
        /// </summary>
        private decimal? _grossWeight;

        private int _cartonQty;


        /// <summary>
        /// 
        /// </summary>
        private PackingListHeader _packingListHeader;
        /// <summary>
        /// 产品
        /// </summary>
        private Product _product;

        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string PackingListDetailId
        {
            get
            {
                return this._packingListDetailId;
            }
            set
            {
                this._packingListDetailId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PackingListHeaderId
        {
            get
            {
                return this._packingListHeaderId;
            }
            set
            {
                this._packingListHeaderId = value;
            }
        }

        /// <summary>
        /// 柜号
        /// </summary>
        public string PLTNo
        {
            get
            {
                return this._pLTNo;
            }
            set
            {
                this._pLTNo = value;
            }
        }

        /// <summary>
        /// 箱号
        /// </summary>
        public string CartonNo
        {
            get
            {
                return this._cartonNo;
            }
            set
            {
                this._cartonNo = value;
            }
        }

        /// <summary>
        /// 客户订单号
        /// </summary>
        public string PONo
        {
            get
            {
                return this._pONo;
            }
            set
            {
                this._pONo = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public decimal? BoxMaxQuantity
        {
            get
            {
                return this._boxMaxQuantity;
            }
            set
            {
                this._boxMaxQuantity = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public decimal? BoxMaxNetWeight
        {
            get
            {
                return this._boxMaxNetWeight;
            }
            set
            {
                this._boxMaxNetWeight = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public decimal? BoxMaxGrossWeight
        {
            get
            {
                return this._boxMaxGrossWeight;
            }
            set
            {
                this._boxMaxGrossWeight = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public decimal? Quantity
        {
            get
            {
                return this._quantity;
            }
            set
            {
                this._quantity = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public decimal? NetWeight
        {
            get
            {
                return this._netWeight;
            }
            set
            {
                this._netWeight = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public decimal? GrossWeight
        {
            get
            {
                return this._grossWeight;
            }
            set
            {
                this._grossWeight = value;
            }
        }

        public int CartonQty
        {
            get { return _cartonQty; }
            set { _cartonQty = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public virtual PackingListHeader PackingListHeader
        {
            get
            {
                return this._packingListHeader;
            }
            set
            {
                this._packingListHeader = value;
            }

        }
        /// <summary>
        /// 产品
        /// </summary>
        public virtual Product Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }

        }
        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PackingListDetailId = "PackingListDetailId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PackingListHeaderId = "PackingListHeaderId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PLTNo = "PLTNo";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_CartonNo = "CartonNo";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PONo = "PONo";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductId = "ProductId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_BoxMaxQuantity = "BoxMaxQuantity";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_BoxMaxNetWeight = "BoxMaxNetWeight";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_BoxMaxGrossWeight = "BoxMaxGrossWeight";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Quantity = "Quantity";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_NetWeight = "NetWeight";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_GrossWeight = "GrossWeight";

        public readonly static string PRO_CartonQty = "CartonQty";

        #endregion


        private string _invoiceXODetailId;

        public string InvoiceXODetailId
        {
            get { return _invoiceXODetailId; }
            set { _invoiceXODetailId = value; }
        }

        private InvoiceXODetail _invoiceXODetail;

        public InvoiceXODetail InvoiceXODetail
        {
            get { return _invoiceXODetail; }
            set { _invoiceXODetail = value; }
        }

        public readonly static string PRO_InvoiceXODetailId = "InvoiceXODetailId";
    }
}