//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PackingInvoiceDetail.autogenerated.cs
// author: mayanjun
// create date：2018/12/2 16:05:26
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PackingInvoiceDetail
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _packingInvoiceDetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _packingInvoiceHeaderId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _number;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pONo;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _quantity;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _unitPrice;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _amount;
		
		/// <summary>
		/// 
		/// </summary>
		private PackingInvoiceHeader _packingInvoiceHeader;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PackingInvoiceDetailId
		{
			get 
			{
				return this._packingInvoiceDetailId;
			}
			set 
			{
				this._packingInvoiceDetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PackingInvoiceHeaderId
		{
			get 
			{
				return this._packingInvoiceHeaderId;
			}
			set 
			{
				this._packingInvoiceHeaderId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Number
		{
			get 
			{
				return this._number;
			}
			set 
			{
				this._number = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PONo
		{
			get 
			{
				return this._pONo;
			}
			set 
			{
				this._pONo = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? Quantity
		{
			get 
			{
				return this._quantity;
			}
			set 
			{
				this._quantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? UnitPrice
		{
			get 
			{
				return this._unitPrice;
			}
			set 
			{
				this._unitPrice = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? Amount
		{
			get 
			{
				return this._amount;
			}
			set 
			{
				this._amount = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public virtual PackingInvoiceHeader PackingInvoiceHeader
		{
			get
			{
				return this._packingInvoiceHeader;
			}
			set
			{
				this._packingInvoiceHeader = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PackingInvoiceDetailId = "PackingInvoiceDetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PackingInvoiceHeaderId = "PackingInvoiceHeaderId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Number = "Number";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PONo = "PONo";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Quantity = "Quantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UnitPrice = "UnitPrice";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Amount = "Amount";
		

		#endregion

        private string _invoiceXODetailId;

        public string InvoiceXODetailId
        {
            get { return _invoiceXODetailId; }
            set { _invoiceXODetailId = value; }
        }

        private InvoiceXODetail _invoiceXODetail;

        public InvoiceXODetail InvoiceXODetail
        {
            get { return _invoiceXODetail; }
            set { _invoiceXODetail = value; }
        }

        public readonly static string PRO_InvoiceXODetailId = "InvoiceXODetailId";
	}
}