//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：Port.autogenerated.cs
// author: mayanjun
// create date：2018/11/11 17:33:42
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class Port
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _portId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _id;
		
		/// <summary>
		/// 
		/// </summary>
		private string _portName;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PortId
		{
			get 
			{
				return this._portId;
			}
			set 
			{
				this._portId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PortName
		{
			get 
			{
				return this._portName;
			}
			set 
			{
				this._portName = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PortId = "PortId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Id = "Id";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PortName = "PortName";
		

		#endregion
	}
}