//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductScrap.autogenerated.cs
// author: mayanjun
// create date：2018-01-14 22:36:51
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ProductScrap
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _productScrapId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _productScrapDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private string _depotId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _note;
		
		/// <summary>
		/// 库房
		/// </summary>
		private Depot _depot;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string ProductScrapId
		{
			get 
			{
				return this._productScrapId;
			}
			set 
			{
				this._productScrapId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? ProductScrapDate
		{
			get 
			{
				return this._productScrapDate;
			}
			set 
			{
				this._productScrapDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string DepotId
		{
			get 
			{
				return this._depotId;
			}
			set 
			{
				this._depotId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Note
		{
			get 
			{
				return this._note;
			}
			set 
			{
				this._note = value;
			}
		}
	
		/// <summary>
		/// 库房
		/// </summary>
		public virtual Depot Depot
		{
			get
			{
				return this._depot;
			}
			set
			{
				this._depot = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductScrapId = "ProductScrapId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductScrapDate = "ProductScrapDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DepotId = "DepotId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Note = "Note";
		

		#endregion
	}
}