//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductItemNo.autogenerated.cs
// author: mayanjun
// create date：2020/11/29 12:58:22
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ProductItemNo
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _itemNo;
		
		/// <summary>
		/// 
		/// </summary>
		private string _internalDescription;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 商品料号
		/// </summary>
		public string ItemNo
		{
			get 
			{
				return this._itemNo;
			}
			set 
			{
				this._itemNo = value;
			}
		}

		/// <summary>
		/// 商品内部描述
		/// </summary>
		public string InternalDescription
		{
			get 
			{
				return this._internalDescription;
			}
			set 
			{
				this._internalDescription = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ItemNo = "ItemNo";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InternalDescription = "InternalDescription";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		

		#endregion
	}
}