//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductBarCodeSet.autogenerated.cs
// author: mayanjun
// create date：2016/3/31 21:50:14
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class ProductBarCodeSet
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private string _productBarCodeSetId;

        /// <summary>
        /// 
        /// </summary>
        private string _nationalCode;

        /// <summary>
        /// 
        /// </summary>
        private string _companyCode;


        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string ProductBarCodeSetId
        {
            get
            {
                return this._productBarCodeSetId;
            }
            set
            {
                this._productBarCodeSetId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string NationalCode
        {
            get
            {
                return this._nationalCode;
            }
            set
            {
                this._nationalCode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string CompanyCode
        {
            get
            {
                return this._companyCode;
            }
            set
            {
                this._companyCode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductBarCodeSetId = "ProductBarCodeSetId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_NationalCode = "NationalCode";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_CompanyCode = "CompanyCode";


        #endregion

        private int? _ValueKey;

        public int? ValueKey
        {
            get { return _ValueKey; }
            set { _ValueKey = value; }
        }
    }
}