//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProformaInvoiceDetail.autogenerated.cs
// author: mayanjun
// create date：2019/3/13 20:30:29
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ProformaInvoiceDetail
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _proformaInvoiceDetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _proformaInvoiceId;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _number;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _quantity;
		
		/// <summary>
		/// 
		/// </summary>
		private string _unit;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _unitPrice;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _amount;
		
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		/// <summary>
		/// 
		/// </summary>
		private ProformaInvoice _proformaInvoice;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string ProformaInvoiceDetailId
		{
			get 
			{
				return this._proformaInvoiceDetailId;
			}
			set 
			{
				this._proformaInvoiceDetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProformaInvoiceId
		{
			get 
			{
				return this._proformaInvoiceId;
			}
			set 
			{
				this._proformaInvoiceId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? Number
		{
			get 
			{
				return this._number;
			}
			set 
			{
				this._number = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? Quantity
		{
			get 
			{
				return this._quantity;
			}
			set 
			{
				this._quantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Unit
		{
			get 
			{
				return this._unit;
			}
			set 
			{
				this._unit = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? UnitPrice
		{
			get 
			{
				return this._unitPrice;
			}
			set 
			{
				this._unitPrice = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? Amount
		{
			get 
			{
				return this._amount;
			}
			set 
			{
				this._amount = value;
			}
		}
	
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public virtual ProformaInvoice ProformaInvoice
		{
			get
			{
				return this._proformaInvoice;
			}
			set
			{
				this._proformaInvoice = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProformaInvoiceDetailId = "ProformaInvoiceDetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProformaInvoiceId = "ProformaInvoiceId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Number = "Number";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Quantity = "Quantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Unit = "Unit";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UnitPrice = "UnitPrice";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Amount = "Amount";
		

		#endregion
	}
}