//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProformaInvoice.autogenerated.cs
// author: mayanjun
// create date：2019/3/13 18:44:59
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ProformaInvoice
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pO;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _invoiceDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _deliveryTo;
		
		/// <summary>
		/// 
		/// </summary>
		private string _currency;

        private string _attn;
		
		/// <summary>
		/// 
		/// </summary>
		private string _remark;
		
		/// <summary>
		/// 
		/// </summary>
		private string _deliveryDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _bankId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _shippimgMark;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;

        private Customer _customer;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PO
		{
			get 
			{
				return this._pO;
			}
			set 
			{
				this._pO = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InvoiceDate
		{
			get 
			{
				return this._invoiceDate;
			}
			set 
			{
				this._invoiceDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string DeliveryTo
		{
			get 
			{
				return this._deliveryTo;
			}
			set 
			{
				this._deliveryTo = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Currency
		{
			get 
			{
				return this._currency;
			}
			set 
			{
				this._currency = value;
			}
        }

        public string Attn
        {
            get { return _attn; }
            set { _attn = value; }
        }

		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get 
			{
				return this._remark;
			}
			set 
			{
				this._remark = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string DeliveryDate
		{
			get 
			{
				return this._deliveryDate;
			}
			set 
			{
				this._deliveryDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string BankId
		{
			get 
			{
				return this._bankId;
			}
			set 
			{
				this._bankId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ShippimgMark
		{
			get 
			{
				return this._shippimgMark;
			}
			set 
			{
				this._shippimgMark = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
        }

        public Customer Customer
        {
            get { return _customer; }
            set { _customer = value; }
        }
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PO = "PO";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceDate = "InvoiceDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_CustomerId = "CustomerId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DeliveryTo = "DeliveryTo";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Currency = "Currency";

        public readonly static string PRO_Attn = "Attn";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Remark = "Remark";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DeliveryDate = "DeliveryDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BankId = "BankId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ShippimgMark = "ShippimgMark";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		

		#endregion
	}
}